# Generated by Django 5.1.3 on 2024-12-10 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='created_at',
            new_name='download_time',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='total_expenses',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='total_income',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='reports',
            name='file_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='file_path',
            field=models.FilePathField(default=django.utils.timezone.now, path='downloads/'),
            preserve_default=False,
        ),
    ]
