# Generated by Django 5.1.3 on 2024-12-09 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_alter_budget_user'),
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminders',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='budgets.budget'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminders',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
