# Generated by Django 5.1.1 on 2024-10-20 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transaction_options_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(choices=[('expense', 'Траты'), ('income', 'Доходы')], on_delete=django.db.models.deletion.CASCADE, to='transactions.transactionstype'),
        ),
    ]
