# Generated by Django 5.1.3 on 2024-12-04 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('transactions', '0012_transactionstype_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='currencies.currency'),
            preserve_default=False,
        ),
    ]
