# Generated by Django 5.1.3 on 2024-12-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-name']},
        ),
    ]
