# Generated by Django 5.1.3 on 2024-12-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_currency_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name']},
        ),
    ]
