# Generated by Django 5.1.1 on 2024-10-05 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at'], 'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['-created_at'], name='budgets_bud_created_b95f08_idx'),
        ),
    ]
