# Generated by Django 5.1.3 on 2024-12-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_transactions', '0002_rename_updated_at_temptransaction_call_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptransaction',
            name='call_time',
            field=models.DateTimeField(),
        ),
    ]
