# Generated by Django 5.1.3 on 2024-12-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_transactions', '0003_alter_temptransaction_call_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('rus_name', models.CharField(max_length=10, unique=True)),
                ('frequency', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='temptransaction',
            name='call_time',
        ),
        migrations.AddField(
            model_name='temptransaction',
            name='frequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='temp_transactions.frequency'),
        ),
    ]
