# Generated by Django 5.1.3 on 2024-12-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_transactions', '0004_frequency_remove_temptransaction_call_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='frequency',
            field=models.IntegerField(max_length=11),
        ),
    ]
