# Generated by Django 5.1.3 on 2024-12-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_transactions', '0005_alter_frequency_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='frequency',
            field=models.IntegerField(),
        ),
    ]
