# Generated by Django 5.1.3 on 2024-12-06 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_transactions', '0008_remove_temptransaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='temptransaction',
            name='last_processed_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
