# Generated by Django 5.1.3 on 2024-12-07 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_transactions', '0011_remove_temptransaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temptransaction',
            name='date_time',
        ),
    ]
