# Generated by Django 5.1.3 on 2024-12-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_transactions', '0012_remove_temptransaction_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='temptransaction',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
