# Generated by Django 5.1.3 on 2024-12-12 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_account_currency'),
        ('currencies', '0003_alter_currency_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currencies.currency'),
        ),
    ]
